name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug AWS Credentials
        run: |
          aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Clean Terraform Cache
        working-directory: setup/terraform
        run: |
          rm -rf .terraform
          rm -f terraform.lock.hcl

      - name: Terraform Init
        working-directory: setup/terraform
        run: terraform init -backend-config=backend.tfvars

      - name: Terraform Validate
        working-directory: setup/terraform
        run: terraform validate -no-color -lock=false

      - name: Terraform Destroy
        working-directory: setup/terraform
        run: terraform destroy -auto-approve -input=false

      - name: Notify on Success
        if: success()
        run: echo "Terraform Destroy completed successfully!"

      - name: Notify on Failure
        if: failure()
        run: echo "Terraform Destroy failed. Please check the logs for errors."
